### ISSUE TITLE
Endless loop in possibly_enlarge

### ISSUE THREAD

**Issue by valerianrossigneux** [dexplo/dataframe_image#78] opened 2023-03-09 03:37 UTC
Hi there, not sure what happened (maybe Chrome update on my MAC), but my code that has been working for years is suddenly going in an endless loop when exporting screenshot through headless chrome.

The possibly_enlarge method never exits, until it crashes:

```
['--disable-gpu', '--headless=old', '--no-sandbox', '--crash-dumps-dir=/tmp', '--force-device-scale-factor=1', '--window-size=1400,900', '--hide-scrollbars', '--screenshot=/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmpj2t92fwz/temp.png', '/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmpj2t92fwz/temp.html']

['--disable-gpu', '--headless=old', '--no-sandbox', '--crash-dumps-dir=/tmp', '--force-device-scale-factor=1', '--window-size=2800,1800', '--hide-scrollbars', '--screenshot=/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmp6kzu8ya_/temp.png', '/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmp6kzu8ya_/temp.html']

...

['--disable-gpu', '--headless=old', '--no-sandbox', '--crash-dumps-dir=/tmp', '--force-device-scale-factor=1', '--window-size=89600,57600', '--hide-scrollbars', '--screenshot=/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmp4d35c9_p/temp.png', '/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmp4d35c9_p/temp.html']
```

**Comment by valerianrossigneux** [comment] 2023-03-09 04:51
After some research it seems the window-size is ignore now if it's larger than the screen's size 
https://groups.google.com/g/chromedriver-users/c/Yro2uGBU1fg

**Comment by araujo-filipe** [comment] 2023-03-09 10:54
+1

**Comment by araujo-filipe** [comment] 2023-03-09 12:05
Since I couldn't use latex as the converter, to go around the issue I installed Brave browser and set its executable as the `chrome_path`. Although not ideal, this fixed it for now.

**Comment by gioxc88** [comment] 2023-03-09 21:54
same issue here

**Comment by gioxc88** [comment] 2023-03-09 22:01
I get this error 

![image](https://user-images.githubusercontent.com/41852601/224170094-45fb6b4d-a96f-4211-bd5b-0ad800e8f66b.png)

**Comment by FrankManc** [comment] 2023-03-10 11:48
> Since I couldn't use latex as the converter, to go around the issue I installed Brave browser and set its executable as the `chrome_path`. Although not ideal, this fixed it for now.

Hi, I just encountered the same issue as you did. I tried to use Brave as an alternative, however, I am quite confused about how do you set chrome_path for Brave Browser?

My laptop is Mac, so I tried chrome_path=r'/Applications/Brave Browser.app', which returns "PermissionError: [Errno 13] Permission denied: '/Applications/Brave Browser.app'"

Thank you

**Comment by PaleNeutron** [comment] 2023-03-10 12:38
It's a problem caused by breaking changes with chrome.

I'll try to diagnose it later but if anyone can provide what actually changed will be very helpful.

**Comment by Neo-Luo** [comment] 2023-03-12 15:26
It is caused by the latest version of Chrome. New Headless Chrome was using the platform window size disregarding --window-size setting if it was larger than the active display work area.

you can use smaller 'fontsize' and greater 'dpi' to skip this problem.
for example:" fontsize=10 and dpi=100" caused this error but the follow settings is helpful for my ‘df' shape.

`dfi.export(df, file_name, fontsize=7, dpi=800, 
           table_conversion='chrome', chrome_path=None)`

**Comment by jorgapa** [comment] 2023-03-14 12:42
Same issue. Brave solution doesn't succeed por me.

**Comment by valerianrossigneux** [comment] 2023-03-14 14:20
@Neo-Luo trick did it for me!

**Comment by benjaminmoritz** [comment] 2023-03-14 19:45
Hi.
Here is the fix.
I followed the idea from @Neo-Luo which is documented here: https://developer.chrome.com/articles/new-headless/
Go to the file `_screenshot.py`  and change `"--headless"` to `"--headless=new"`
The documenation from google says, that if you do not provide the "=new" then it will automatically use "=old"
![image](https://user-images.githubusercontent.com/42141919/225117698-a5f8264e-4b23-404b-a912-a5f57f576743.png)

**Comment by valerianrossigneux** [comment] 2023-04-05 01:33
@benjaminmoritz This didn't work for me, it actually now raises an exception with the new code published 3 days ago.
It would be great to pass the args to the export funciton so that these can be overwritten as necessary:

`Exception: Command '['--enable-logging', '--disable-gpu', '--headless=new', '--crash-dumps-dir=/tmp', '--force-device-scale-factor=8.0', '--window-size=1400,900', '--hide-scrollbars', '--screenshot=/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmpvcrdt825/temp.png', '/var/folders/2t/fn3dx6l52rv8rslqclwvhm0w0000gn/T/tmpvcrdt825/temp.html']' returned non-zero exit status 21.



`

**Comment by PaleNeutron** [comment] 2023-09-12 07:22
I think it should be marked as fixed since chrome fix it after  version 113 and we provide more convert method opthions.

**Closed by PaleNeutron** 2023-09-12 07:22 UTC
Labels: bug, help wanted
